# Configuration du serveur Paper - Lobby
# Version: 1.20.6

# Propriétés de base
server-name=Lobby
motd=§6§lBienvenue sur DevVanilla! §7§oChoisissez un mode de jeu...
max-players=50
gamemode=adventure
difficulty=peaceful
enable-command-block=true
pvp=false
enable-rcon=false

# Propriétés réseau
server-port=25568
server-ip=
online-mode=true
allow-flight=true
allow-nether=false
resource-pack=
resource-pack-sha1=

# Propriétés du monde
type=FLAT
level-name=world_lobby
level-seed=
level-type=flat
generator-settings={"layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:stone","height":1},{"block":"minecraft:polished_diorite","height":1}],"biome":"minecraft:plains"}

# Propriétés des joueurs
hardcore=false
enable-bungeecord=true
prevent-proxy-connections=false

# Propriétés de la console
rcon.password=
rcon.port=25578

# Propriétés de la sauvegarde
auto-save=false

# Propriétés des logs
log-ip-addresses=true
